{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ecs:UpdateService",
        "ecs:DescribeServices"
      ],
      "Resource": "arn:aws:ecs:us-east-1:218705140181:service/python-demo-cluster/*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ecs:TagResource"
      ],
      "Resource": "arn:aws:ecs:us-east-1:218705140181:task-definition/python-demo-app:*"
    }
  ]
}